### ISSUE TITLE
Member for new events in different groups

### ISSUE THREAD

**Issue by Tracker-HM** [netzfisch/teamorga#3]
Ich bin zu müde...
Die Anzahl der möglichen Teilnehmer an einem Event in einer anderen Gruppe als dem ATSV ist auch immer 14 mit den gleichen vorgegebenen Teilnehmern bei "Wir brauchen mehr Bier/Leute". Hier müssten eigentlich nur die Teilnehmer der jeweiligen Gruppe gezählt werden, die
- eine Trikotnummer haben und
- zur Gruppe gehören und damit auch zwangsläufig eine Änderung der eMail-Linkliste (s.o.) nach sich ziehen.

In meinen neu angelegten Gruppen sollte die Anzahl -noch keine Testuser angelegt- demnach 1 und nicht 14 sein.

**Comment by netzfisch** [comment]
This is obviously a bug, I will fix it the next days!

By the way - I will remove the logic counting just people with trikot-numbers for playday feedback, because people envolved in different teams,
- could in one group participate on playdays
- as on an other group won't participate!

So the trikot number is more or less not usefull as indicator anymore and could be removed!

**Comment by netzfisch** [comment]
Done, counts now all members of the belonging group. Now, there is no difference between users with/without licence number!
